backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "showcase"
    label: "Showcase"
    folder: "content/showcase"
    create: true  # Set to false since it's a single file
    fields:
      - { label: "Enable", name: "enable", widget: "boolean" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - { label: "Image", name: "x", widget: "image" }
          - { label: "Retina Image", name: "_2x", widget: "image" }
      - label: "Mobile Image"
        name: "imageMobile"
        widget: "object"
        fields:
          - { label: "Mobile Image", name: "x", widget: "image" }
      - label: "Button"
        name: "button"
        widget: "object"
        fields:
          - { label: "Icon", name: "icon", widget: "string" }
          - { label: "Button Text", name: "btnText", widget: "string" }
          - { label: "URL", name: "URL", widget: "string" }
      - label: "Social Links"
        name: "socialLinks"
        widget: "list"
        fields:
          - { label: "Icon", name: "icon", widget: "string" }
          - { label: "URL", name: "URL", widget: "string" }
